### ISSUE TITLE
BepInEx v.5.0 RC1大更新，進遊戲前報錯

### ISSUE THREAD

**Issue by Rainbow2408** [higankanshi/MaidTranslation#3]
> [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'MaidTranslate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
ImportCM.CreateTexture (System.String f_strFileName)
CasinoShopItem..ctor (.CsvParser csv, Int32 cy)
CasinoDataMgr.InitShopData ()
GameMain.OnInitialize ()
MonoSingleton\`1[GameMain].Initialize (.GameMain instance)
MonoSingleton\`1[T].Awake ()

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MessageWindowMgr.Awake ()

> [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'MaidTranslate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:SetActive(Boolean)
TutorialPanel:Awake()

> [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'MaidTranslate, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:

**Comment by devkanro** [comment]
这个更新害人不浅，好多东西都改了，很是无奈
跟着 5.0 更新了一个版本，之后我的版本也随着 BepInEX 的版本号走了

https://github.com/devkanro/MaidTranslate/releases/tag/MaidTranslate-v5.0
